# Deployment controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp #Can be the name we need to keep for the deployment controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: react #Can be the name we have in our container spec
  template:
    metadata:
      name: webapp
      labels:
        application: react

    spec:
      containers:
        - name: webapp
          image: docker.io/dpthub/dpt7-react-app:latest

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      
            limits:
              memory: "128Mi"
              cpu: "500m"

          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20


