apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-micro-services-admin
  labels:
    app: eos-micro-services-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-micro-services-admin
  template:
    metadata:
      labels:
        app: eos-micro-services-admin
    spec:
      containers:
      - name: eos-micro-services-admin
        image: docker.io/dpthub/eos-micro-services-admin:latest
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: eos-micro-services-admin-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 8090
  selector:
    app: eos-micro-services-admin
